M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sat 08 Feb 2025 07:00:28 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-08T19:00:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X3.82Y-3.44
X6.9094Y-1.5354
M30
